### ISSUE TITLE
FAIL:  Service snap.microk8s.daemon-k8s-dqlite is not running

### ISSUE THREAD

**Issue by fabianonetto** [canonical/k8s-dqlite#22]
Hi everyone, I'm setting up a local lab with 2 laptops running Ubuntu 20.04 server and microk8s in a multi-node cluster being 1 server and 1 agent. 

On the agent node, when running `microk8s inspect` I get the following output:
`FAIL:  Service snap.microk8s.daemon-k8s-dqlite is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-k8s-dqlite`

Looking for more details on the journal as per the output above I got the following:
[snap.microk8s.daemon-k8s-dqlite.journal.log](https://github.com/canonical/k8s-dqlite/files/8310080/snap.microk8s.daemon-k8s-dqlite.journal.log)

I have no idea what can be going wrong or what I am missing. Appreciate any help.

Thanks

**Comment by balchua** [comment]
@fabianonetto 
Looking at your log, the service `k8s-dqlite` is not expected to start.  There are 2 reasons why this is happening:
* You have configured your cluster to run in **non** HA mode, which means it has one control plane and uses etcd instead of dqlite.  So in your case the "agent" node will not run dqlite.
* When you join a node, you explicitly joined it with `--worker`.  In this case this particular "agent" node, it will not have the control plane components, controller, scheduler, api server and dqlite.

These are all normal behaviors.

**Comment by fabianonetto** [comment]
> @fabianonetto 
> Looking at your log, the service `k8s-dqlite` is not expected to start.  There are 2 reasons why this is happening:
> * You have configured your cluster to run in **non** HA mode, which means it has one control plane and uses etcd instead of dqlite.  So in your case the "agent" node will not run dqlite.
> * When you join a node, you explicitly joined it with `--worker`.  In this case this particular "agent" node, it will not have the control plane components, controller, scheduler, api server and dqlite.
> 
> These are all normal behaviors.

Thank you
